#syntax=docker/dockerfile:1
FROM golang:1.21.8

ENV GO111MODULE=on
ENV GOFLAGS=-mod=vendor
ENV APP_HOME = /go/src/quizzapp
RUN mkdir -p "$APP_HOME"

WORKDIR "$APP_HOME"
COPY ./src ./

RUN go build -o quizzapp_bin .
RUN pwd
RUN ls -la
EXPOSE 8000

ENTRYPOINT [ "./quizzapp_bin" ]

# http://172.17.0.2:8000/