#syntax=docker/dockerfile:1
FROM golang:1.21.8


ENV GO111MODULE=on
ENV GOFLAGS=-mod=vendor
ENV APP_HOME = /go/src/quizzapp
RUN mkdir -p "$APP_HOME"

WORKDIR "$APP_HOME"
COPY ./src ./
RUN pwd

RUN go mod download -x 

RUN go build -o quizzapp_bin .

EXPOSE 8000

ENTRYPOINT [ "/app/quizzapp_bin" ]